
USE OSCAR_BOTELLO;

#CREATE TABLE FLIA_BOTELLO(

#ID_FAMILIAR double NOT NULL,
 #NOMBRE varchar (10) NOT NULL,
 #APELLIDO varchar (10) NOT NULL,
 #PARENTESCO varchar (10) NOT NULL,
 #SEXO varchar (10) NOT NULL,
 #FECHA_DE_NACIMIENTO varchar (10) NOT NULL);
 
 
#INSERT INTO FLIA_BOTELLO 
#VALUES(8,"STEVE","CANO","PRIMO","MASCULINO","12/05/1985")

SELECT*FROM FLIA_BOTELLO;
 